<?php
/**
 * @file
 * taxonomy_neighborhood.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function taxonomy_neighborhood_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'North Druid Valley',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0656d198-4770-4a12-bf6a-1670d108333e',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Gwinnett',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '08371948-4056-4a76-acfa-a49af7f2f079',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'South Atlanta Neighborhood',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '17397017-385b-410c-9df0-c9f439a69ca1',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Clarkston',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '197ca217-45c1-4072-adc9-ca1b8f9f6727',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'AU Center',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '26609c0c-c5c6-4be3-aa7e-867a2f7bbb93',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'DeKalb County',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '32c3f510-a999-4758-986b-b2fd91784053',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'NPU-V',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '43a04b24-662a-4fc9-8b6e-708a3b1d3669',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Oakhurst',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4665237d-091c-4914-a902-3ad288e3eaba',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Fulton County',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '544aab54-adff-4764-94b0-96794bab11bd',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Fayetteville',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '55c462ef-25bb-43e5-8e38-f0f01e6cb5b6',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Norcross Mobile Home Park',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5d84abaa-bc4a-4cd2-9ee2-a588c35c607c',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Fayette FACTOR',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '637e2ed6-06d2-4130-abda-6ae5e372e421',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'NPU-H ADAMSVILLE',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '63c661e3-889f-4196-95ac-951b88560e50',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Southwest Atlanta',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '653abce0-7f0c-4b97-94c6-ac2bc914a92a',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Stone mountain',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '670e644e-6c63-413e-8233-f6d38cf2ed77',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Sandy Springs',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '72fbf44d-bc35-40f2-b645-ac49d470d928',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Old Fourth Ward',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '73f3d8d6-a58c-4d71-8600-6f3ba00f2f86',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'North Fulton County',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '73f91400-a6ac-4f5d-a13c-66c4da04b894',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'NPU-L',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7f5a87a6-df45-420f-a82c-ef5f116e9c72',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Atlanta Region',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8ff2f231-7a60-4b63-b1e4-31593607bb8f',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Lilburn',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '92197cc0-6034-4942-9513-4a7a9270e6ce',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Edgewood',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '956fa648-aad3-498c-b1a9-cfde730a8be7',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Metro Atlanta',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '996cc308-bea5-4461-843f-21b8fbf39bd1',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'South Forsyth',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '99d3fc69-abe7-4cdd-889e-8690d15296ea',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Decatur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a349751b-f6c7-4fe9-bc00-bb7a97872633',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Norcross Mobile Home Village',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b520638c-2107-4dc2-b759-d04c5659561e',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'South Atlanta',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'bcd2bc7c-cb5e-4113-b747-9a6e05fd80c2',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Newton County',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'be5bb102-de9b-4870-9e69-2428d2f5d6bd',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'NPU-L: English Avenue and Vine City',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cf8527b0-dd21-4339-87af-65d8bc5bd67e',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Midtown',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'da4e7aee-6049-4473-9f29-78704026bd09',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Downtown Atlanta',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'dc15459c-d18e-4608-a51f-5744440bb1e6',
    'vocabulary_machine_name' => 'neighborhood',
  );
  $terms[] = array(
    'name' => 'Norcross',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e340cd02-4d06-4146-8114-71bf503400cb',
    'vocabulary_machine_name' => 'neighborhood',
  );
  return $terms;
}
