<?php
/**
 * @file
 * taxonomy_county.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function taxonomy_county_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'DeKalb',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0595eaae-8eee-4ab8-b33a-498ffa99de29',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Douglas',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1b6dbd68-2878-4db9-a889-02ffa3aab6bc',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Paulding',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1bfd644c-cf7c-42b5-84e7-a50e737fb993',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Morgan',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '334a5ab5-8677-4b68-acfd-e51816280be9',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Fulton',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '336c889e-bddd-4ebb-9d54-5607ec572fff',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Barrow',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '383ed32a-7759-47af-aa4f-817cd98750a6',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Hall',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4083c071-d470-4d1f-9367-8cd262da9ded',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Coweta',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '438379cc-19e1-4ca8-9502-fbe502323cb8',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Cherokee',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '49628bbd-b022-4c92-ab6e-596d672438aa',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Rockdale',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4bca0245-6158-4746-a9c3-5a432918081c',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Walton',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6e9eb700-c060-47e9-a64d-a3461439c8d1',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Gwinnett',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7182b9ba-28ee-4027-9d7e-469626ce6eb6',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Cobb',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '77377ebf-27fe-48a4-a829-9ed3fca3c24b',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Clayton',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '79143a75-5e49-438d-a91b-945aed92754b',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Spalding',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7d3e1a06-5a35-4ffa-b3b5-e850aaf24e39',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Bartow',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '92095481-1f80-4507-91d3-426d2e8a6f1f',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Fayette',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9546bbaf-31ea-4b0d-9bd4-a5d898002e4b',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Henry',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9eb74955-e08c-49d8-bdfa-f7c076b5c46b',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Newton',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a3d63292-c8af-43ba-84ba-e6d212f75b73',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Forsyth',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b29a635a-3327-4bfb-b58d-c28013ff0a36',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Carroll',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c9b81eeb-2c2c-4068-b106-6d67d3f4b089',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Butts',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e76acfa5-a47f-4048-bce2-a3709c1bda1b',
    'vocabulary_machine_name' => 'county',
  );
  $terms[] = array(
    'name' => 'Pickens',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e8deb0a6-a91d-479b-9f16-7eea9e3cadd8',
    'vocabulary_machine_name' => 'county',
  );
  return $terms;
}
